lib/emplo_reward_web/router.ex
defmodule EmploRewardWeb.Router do
  use EmploRewardWeb, :router

  import EmploRewardWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {EmploRewardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user, :redirect_if_user_is_admin]

    get "/", UserMainPageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", EmploRewardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: EmploRewardWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  ## Points routes

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user, :redirect_if_user_is_admin]

    post "/users/add_points", UserAddPointsController, :add
    get "/rewards", RewardController, :index
    get "/:reward_id/get_reward", RewardController, :grant_reward
    get "/rewards/history", RewardHistoryController, :user_history

    end

    scope "/", EmploRewardWeb do
      pipe_through [:browser, :require_admin_user]
      get "/rewards/admin_list", RewardController, :admin_index
      get "/rewards/:id/edit", RewardController, :edit
      get "/rewards/new", RewardController, :new
      post "/rewards", RewardController, :create
      patch "/rewards/:id", RewardController, :update
      put "/rewards/:id", RewardController, :update
      delete "/rewards/:id", RewardController, :delete
      get "/rewards/history/admin", RewardHistoryController, :admin_history
    end

end

lib/emplo_reward_web/views/layout_view.ex
defmodule EmploRewardWeb.LayoutView do
  use EmploRewardWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/emplo_reward_web/templates/layout/_user_menu.html.heex
<%= if @current_user do %>
<p class="border border-3 border-dark rounded fw-bold px-2 shadow-sm mt-2">
  <strong>Logged as: </strong><%= @current_user.full_name %> |
  <strong>Your points: </strong> <%= @current_user.points_granted %> |
  <strong>Points to spend: </strong> <%= @current_user.points%>
</p>
<ul class="nav justify-content-end">
  <li class="nav-item rounded m-1 hover fw-bold">
    <%= link "Rewards", to: Routes.reward_path(@conn, :index), class: "nav-link link-dark", style: "text-decoration: none;" %>
  </li>
  <li class="nav-item rounded m-1 hover fw-bold">
    <%= if @current_user.role == "member" do %>
    <%= link "Rewards History", to: Routes.reward_history_path(@conn, :user_history), class: "nav-link link-dark", style: "text-decoration: none;" %>
    <% else %>
    <%= link "Rewards History", to: Routes.reward_history_path(@conn, :admin_history), class: "nav-link link-dark", style: "text-decoration: none;" %>
    <% end %>
  </li>
  <li class="nav-item rounded m-1 hover fw-bold">
    <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "nav-link link-dark", style: "text-decoration: none;" %>
  </li>
  <li class="nav-item rounded m-1 hover fw-bold">
    <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "nav-link link-dark", style: "text-decoration: none;" %>
  </li>
</ul> 
<% else %>
<ul class="nav justify-content-center">
  <li class="nav-item rounded m-1 fw-bold hover">
    <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "nav-link active link-dark", style: "text-decoration: none;" %>
  </li>
  <li class="nav-item rounded m-1 fw-bold hover">
    <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "nav-link link-dark", style: "text-decoration: none;" %>
  </li>
</ul>
<% end %>

lib/emplo_reward_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info mx-auto my-3 col-8" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger mx-auto my-3 col-8" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/emplo_reward_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/emplo_reward_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "EmploReward", suffix: " · Phoenix Framework" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/style.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <div class="container-fluid pb-2 mb-4 bg-secondary shadow border-bottom border-dark">
        <div class="row justify-content-center">
          <div class="col-xxl-4 col-xl-12 col-lg-12 col-md-12 d-none d-sm-block" >
            <a href={Routes.user_main_page_path(@conn, :index)} class="emplo-logo">
              <img src={Routes.static_path(@conn, "/images/logo.png")} alt="Emplo Reward Logo"/>
            </a>
          </div>
          <div class="col-xxl-4 col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 my-auto">
            <%= render "_user_menu.html", assigns %>
          </div>
        </div>
      </div>
    </header>

    <%= @inner_content %>
  
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 m-2 border-top fixed-bottom">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
        </a>
        <span class="text-muted">&copy; 2022 EmploReward | Created By: Jakub Łobodziński</span>
      </div>
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="https://github.com/KubaLobodzinski"><svg class="bi" width="24" height="24"><use xlink:href="#github"/></svg></a></li>
      </ul>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <symbol id="github">
          <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
        </symbol>  
      </svg>
    </footer>
  </body>
</html>