lib/emplo_reward_web/router.ex
defmodule EmploRewardWeb.Router do
  use EmploRewardWeb, :router

  import EmploRewardWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {EmploRewardWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user, :redirect_if_user_is_admin]

    get "/", UserMainPageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", EmploRewardWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: EmploRewardWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", EmploRewardWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  ## Points routes

  scope "/", EmploRewardWeb do
    pipe_through [:browser, :require_authenticated_user, :redirect_if_user_is_admin]

    post "/users/add_points", UserAddPointsController, :add
    get "/rewards", RewardController, :index
    get "/:reward_id/get_reward", RewardController, :grant_reward
    get "/rewards/history", RewardHistoryController, :user_history

    end

    scope "/", EmploRewardWeb do
      pipe_through [:browser, :require_admin_user]
      get "/rewards/admin_list", RewardController, :admin_index
      get "/rewards/:id/edit", RewardController, :edit
      get "/rewards/new", RewardController, :new
      post "/rewards", RewardController, :create
      patch "/rewards/:id", RewardController, :update
      put "/rewards/:id", RewardController, :update
      delete "/rewards/:id", RewardController, :delete
      get "/rewards/history/admin", RewardHistoryController, :admin_history
    end

end

lib/emplo_reward_web/controllers/user_main_page_controller.ex
defmodule EmploRewardWeb.UserMainPageController do
  use EmploRewardWeb, :controller

  alias EmploReward.Accounts
  alias EmploReward.Accounts.User



  def index(conn, _params) do
    users = Accounts.get_all_users()
    |> Enum.sort_by(fn x -> x.full_name end)

    changeset = User.points_changeset(%User{})

    render conn, "index.html", users: users, changeset: changeset
  end

end

lib/emplo_reward_web/views/user_main_page_view.ex
defmodule EmploRewardWeb.UserMainPageView do
  use EmploRewardWeb, :view
end

lib/emplo_reward_web/templates/user_main_page/index.html.heex
<%# Displaying users from database and adding forms to grant them points %>

<div class="container">
  <div class="row justify-content-center">
    <%= for user <- @users do %>
    <%= if user != @current_user && user.role == "member" do %>
    <div class="col-xxl-5 col-xl-5 col-md-12 m-3 border border-2 rounded border-dark hover shadow">
      <div class="img">
        <img src={Routes.static_path(@conn, "/images/image.jpg")} class="img-thumbnail float-start my-2" style="width: 200px; height: 200px;" alt="Person's photo" />
      </div>
      <div class="text-center pt-2">
        <h5>
         <p><strong><%= user.full_name %></strong></p> 
        </h5>
        <hr>
      </div>
      <div class="row mt-5 text-center">
        <%= form_for @changeset, Routes.user_add_points_path(@conn, :add), fn f ->  %>
        <%= range_input f, :points_granted, min: 0, max: @current_user.points, value: 0, step: 1, oninput: "this.nextElementSibling.value = this.value", class: "range" %>
        <output></output>
        <%= hidden_input f, :id, value: user.id %>
        <p>
          <%= submit "Grant points", class: "btn btn-secondary"%>
        </p>
        <% end %>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>